### ISSUE TITLE
PDF Signature 1 Not valid after second signer signs document

### ISSUE THREAD

**Issue by hknobbe** [docusealco/docuseal#163]
Hi!

I've just noticed that as soon as a seccond party signs a document that has been signed by a first party, the first signature becomes invalid because the "pages have been altered". See sample document.

[Bruikleenovereenkomst-5.pdf](https://github.com/docusealco/docuseal/files/13671964/Bruikleenovereenkomst-5.pdf)

I've checked this with a document by another signing software and in that document the signatures stay valid. See the screenshot

![signatures](https://github.com/docusealco/docuseal/assets/39634152/31bc7d75-322b-4fa3-873b-549f4fb3b54d)

I don't know if this is something that could be changed on your side, or if this is because there isn't a valid AATL cert?

**Comment by omohokcoj** [comment]
@hknobbe can you please share a PDF file with 3 signatures you have on the screenshot?

**Comment by hknobbe** [comment]
@omohokcoj any way I can get it privately to you? It's an official document. Not really something to put openly on GitHub.

**Comment by omohokcoj** [comment]
@hknobbe would appreciate it a lot if you could DM me it on Discord:
https://discord.gg/qygYCDGck9

**Comment by omohokcoj** [comment]
@hknobbe we added an option to apply single signature once the document has been signed by all parties.

Adobe allows only to fill existing PDF form fields - all other page modifications will cause existing signatures to be displayed as broken (though you can validate a signature if you view the document version when the signature was added with the incremental updates we use).

In our case PDF form fields are not sufficient because we have field types like image and file attachments which can't be added via fields.

![image](https://github.com/docusealco/docuseal/assets/5418788/17d78888-4aee-4239-837f-2f14efb89e58)
It has been released in the latest 1.3.5 version

**Comment by wrigjz** [comment]
Would a different way to solve this to be to have all but the last signatures as electronic only and then the final signature to be digital so there is only one digital signature for the entire document and that one made after all the fields are added and therefore is valid?

**Comment by omohokcoj** [comment]
@wrigjz yeah applying just a single digital signature in the end once the all fields are filled by all parties solved this - we added a toggle button to enable a 'single signature' mode
