### ISSUE TITLE
UETA and ESIGN Act

### ISSUE THREAD

**Issue by grintor** [docusealco/docuseal#246]
I've reviewed your SaaS offering for compliance and I've noted two issues you have that run the product astray of the regulations.

1) When using the "Set Signing Date" option, what the signer sees in the date field when signing is "{{date}}" (even after they have signed), but in the downloaded PDF, that field is populated with today's date. It's not permitted for the document contain different information than what was presented to the user.

2) When using the "stamp" feature, Docuseal will certify that a user has electronically signed the document even if they did not sign it, but only filled out a text field.

_Originally posted by @grintor in https://github.com/docusealco/docuseal/issues/228#issuecomment-2028539221_

**Comment by omohokcoj** [comment]
@grintor thanks for opening the issue:
1. In the new release in the Cloud and Self-hosted current date is displayed instead of {{date}}
2. We do not limit the use of the stamp fields and it's up to the user of the tool to utilize it in compliance with their local electronic signature laws. For example based on eIDAS (EU) printing a name in the text fields and clicking on a checkbox to sign can be considered as a electronic signature (simple level) - so adding a Stamp stating that the document was signed makes sense in that context even when the document doesn't contain a 'drawn' signature.
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/eSignature+FAQ (simple eIDAS signature)

**Comment by grintor** [comment]
The problem now is that the date field that belongs to users who have not yet signed is populated with today's date. This means that if I sign a document for which there are two signers and I print out my copy, then the next day signer two signs the document, then my copy has information on it (the signer two date) that differs from the data in the same location of signer two's copy.

The {{date}} field for any signer who may be signing in the future (except the person who is signing right now) needs to be blank until they sign.

**Comment by omohokcoj** [comment]
@grintor thanks for pointing this out - it has been fixed in the Cloud and will be included in the next open-source release on Monday.

**Comment by omohokcoj** [comment]
Closing since the mentioned issuers have been resolved. Please reopen to report any other related issuer.
