### ISSUE TITLE
Can Not Replace PDF Documents or Images After Initial Upload

### ISSUE THREAD

**Issue by CorbinIvon** [docusealco/docuseal#26]
After the initial upload, I realized that you can't replace the PDF with a different PDF.

The form I'm uploading would be the same (the template), but the content would change occasionally. It's a fairly large document and small things are changed every now and then.

It would be great if I could just upload a different document and keep the input fields right where I left them instead of having to create a new template...

Even if there was a small "Replace" button, that would be great!

Thank you,
Corbin Meier.

**Comment by Gigaion** [comment]
I like Corbin's suggestion. Although assuming this submissed gets accepted, I'd like to see the page buttons "Copy Share Link" and "+ Add Recipients" get moved to each individual submission so that the functionality is correct.

![example1](https://github.com/docusealco/docuseal/assets/36256725/ee9842a8-8fc3-4bad-8377-481194affe60)

**Comment by AlexandrToorchyn** [comment]
@CorbinIvon In the last release, I added the ability to change documents without losing previously defined fields. Hope you can give it a try.

**Comment by CorbinIvon** [comment]
Wonderful! Thank you @AlexandrToorchyn. I'll need to give it a try as soon as I can!
