### ISSUE TITLE
[Feature] Ability to markup a document without signer being able to edit it.

### ISSUE THREAD

**Issue by cfredericksen** [docusealco/docuseal#28]
I would like to copy a template, add some text specific to the document then send it to be signed. The added text should not be modifiable by the signer.

**Comment by AlexandrToorchyn** [comment]
@cfredericksen This idea really makes sense and can be very useful, but at this stage of development I cannot implement it because it will significantly change the vector of my development.

As an alternative for you, I can recommend you to add 2 submitters to the template and fill in your customer details on behalf of one submitter. It's not exactly the right way, but you could try.

![2_submitters](https://github.com/docusealco/docuseal/assets/1176367/f0b1fcdf-5841-4613-a354-32d583c175dc)

**Comment by cfredericksen** [comment]
Thanks for the workaround! Works great.
