### ISSUE TITLE
Signature is invalid when opened in adobe acrobat reader

### ISSUE THREAD

**Issue by amuletxheart** [docusealco/docuseal#299]
I had a document signed using Docuseal rejected by a legal firm because not all 3 human signatures are validated under 1 digital signature.

I think what Docuseal does is it creates 3 revisions with the first digital signature used to validate the first revision, the second digital signature validate the second revision and so on.

Is this the correct way of doing things and is compliance with existing legal requirements? 

Thanks. I'm hoping for a viable replacement for Docusign and looking forward to product improvements.

<img width="432" alt="Screenshot 2024-06-20 at 12 41 45 PM" src="https://github.com/docusealco/docuseal/assets/5906627/8b419cdb-2a12-49c2-b1c1-6ff2be0615e7">

**Comment by omohokcoj** [comment]
@amuletxheart it seems like you're using DocuSeal in the multiple signatures mode - this way the app creates 3 PDF revisions and applies multiple digital signatures to the document. In Adobe Reader previous signatures are displayed as invalid since adding a new signature modifies the document - but those signatures can be verified on the revision view or on the /settings/esignature page.

A single/final digital signature can be toggled on the /settings/esign page - this mode is turned on by default for all new accounts. Also that's how other eSignature SaaS work by applying just the final signature so that Adobe doesn't show error messages (even though those are technically not errors and individual signatures/revisions still can be verified).

You can toggle off the multiple signatures mode to make docuseal digital signatures work just like any other mainstream esignature SaaS:
![image](https://github.com/docusealco/docuseal/assets/5418788/1f758073-4bf7-4b91-9d44-28cb722e4a02)



Let me know if you have any questions
