### ISSUE TITLE
Migrations not being applied

### ISSUE THREAD

**Issue by thecircleisround** [docusealco/docuseal#319]
Recently tried to update to the latest (been on 1.5.2) and am getting a postgres error when rails attempts to migrate the db. 

````
 /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params': PG::ForeignKeyViolation: ERROR:  insert or update on table "account_linked_accounts" violates foreign key constraint "fk_rails_babfe524b4" (ActiveRecord::InvalidForeignKey)
app-1        | DETAIL:  Key (account_id)=(1) is not present in table "accounts". ````

**Comment by omohokcoj** [comment]
Hi @thecircleisround we assume that your database contains an account with ID 1 (since in every new app the first account with ID: 1 is created after the initial setup).

It looks like you've modified your database tables/rows via SQL so that you don't have an account with ID 1.
Reverting back your manual DB changes or creating a new account with SQL insert and ID 1 should fix the migration.

https://github.com/docusealco/docuseal/blob/master/db/migrate/20240428112400_populate_account_linked_accounts.rb#L19

**Comment by thecircleisround** [comment]
I haven't altered the db in any way. I reverted back to 1.5.2 and it works fine.

**Comment by thecircleisround** [comment]
After inspecting the db it looks like my primary and test account have ids 2 and 3 respectively. There is no account with id 1. I did not alter the db to set to this so not sure why this would be the case

**Comment by omohokcoj** [comment]
@thecircleisround thanks for sharing this - it's possible that during the initial setup there was an error that caused the Account ID sequence to become incremented by +1 without creating a new account row (edge case).
To fix the migration - Insert a new acocunt with ID: 1 - run the migration and then remove it.
Also you might need to update the IDs in the account_linked_acconts table row.

**Comment by thecircleisround** [comment]
Thanks. I did an insert with account id. Is account_linked_accounts the only place where there would be a FK to the accounts table?

**Comment by omohokcoj** [comment]
@thecircleisround yes account_linked_accounts is the only place with account:1 FK - you need to change it from 1 to 2
