### ISSUE TITLE
Lines below the signature pushed together in separate documents

### ISSUE THREAD

**Issue by EduNetEurope** [docusealco/docuseal#343]
Hi,

In the separate documents, the lines below the signature are consistenly pushed together and overlapping. In the combined document, they are displayed correctly.

**Comment by omohokcoj** [comment]
@EduNetEurope can you share the document or a screenshot as well as your app version (Cloud or self-hosted docker)

**Comment by EduNetEurope** [comment]
Cloud, 1.69.
I will email a file to the support email address.

**Comment by omohokcoj** [comment]
@EduNetEurope you need to run the app using docuseal/docuseal docker to ensure everything works correctly - the issue with the font/lines is because you're not running it in docker

**Comment by nebulade** [comment]
Just backlinking this to our forum as @EduNetEurope runs DocuSeal on Cloudron: https://forum.cloudron.io/topic/12338/lines-below-signature-pushed-together-overlapping

Potentially our package lacks some fonts then as @omohokcoj indicates. We will investigate.

**Comment by omohokcoj** [comment]
@nebulade thanks for the heads up - didn't realize it was the Cloudron app (the same issue also happens when using without docker)

That's true that the font building step is required to display text correctly in the PDF:
https://github.com/docusealco/docuseal/blob/master/Dockerfile#L1 - here we have the fonts building step
https://github.com/docusealco/docuseal/blob/master/Dockerfile#L72 - fonts are copied here

Let me know if there is anything else I can provide to help to resolve the issue.

**Comment by nebulade** [comment]
We have added the font building steps by now, however the line height or line padding seems to be still slightly different in the signature flow vs the output pdf, some users report that on their pdf viewer the lines are even more stashed together. Is this to be expected? I am not an expert on how pdf handles such things.

![image](https://github.com/user-attachments/assets/2c3ee429-add6-458a-beec-eb78dfa6f80a)

output:

![image](https://github.com/user-attachments/assets/5ad9ac32-a0ee-4bcb-be23-5bbf1eb3078a)

**Comment by omohokcoj** [comment]
@nebulade it seems like the font files are downloaded into the `/app/code/app/public/fonts/` directory in Cloudron docker image.
Fonts path is hardcoded to /fonts root directory in the app - so downloading font files into /fonts instead of /app/code/app/public/fonts/ should solve the issue

https://git.cloudron.io/cloudron/docuseal-app/-/blob/main/Dockerfile?ref_type=heads#L41
https://github.com/docusealco/docuseal/blob/master/lib/submissions/generate_result_attachments.rb#L6

**Comment by EduNetEurope** [comment]
@omohokcoj Thanks! And thanks to @nebulade for putting the font files in the root directory. :-)

**Comment by nebulade** [comment]
@omohokcoj ah this is great insight! And indeed placing the fonts in `/fonts` solves the issue. Thanks a lot for taking the effort to look into this!
