### ISSUE TITLE
Issue on date format

### ISSUE THREAD

**Issue by DarshanKBhattt** [docusealco/docuseal#377]
Date format should be dd-MM-yyyy and it is but we can enter maximum 6 number and there is not limit I can add date 27-08-999999 so someone please fix this.

![image](https://github.com/user-attachments/assets/ebe8bf7d-6511-4355-84a4-3d99bd516914)
 I hope you can see image 

Actually I am Android developer so 😅

**Comment by omohokcoj** [comment]
@DarshanKBhattt thanks for reporting this, 08/26/275760 is a validation date

**Comment by DarshanKBhattt** [comment]
So am I misunderstood something but I think 6 digit year is wrong format

**Comment by sirthias** [comment]
> @DarshanKBhattt thanks for reporting this, 08/26/275760 is a valid date

Well, technically and from an academic perspective it might be.
But from a user and business perspective it is certainly not a valid date.
And this Docuseal is a business tool and not something to -- say -- compute astronomical data Docuseal should not allow 5 or 6-digit years, since they will NEVER (and I really mean NEVER) be correct at any point in the lifetime of this project.
